version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: tricount-postgres-db
    environment:
      POSTGRES_DB: tricount
      POSTGRES_USER: tricount
      POSTGRES_PASSWORD: tricount
    ports:
      - "5432:5432"
  
  #feicount:
  #  image: feicount:latest
  #  container_name: tricount-feicount
  #  environment:
  #    "ConnectionStrings:DefaultConnection": "Host=postgres;Port=5432;Database=feicount;Username=tricount;Password=tricount;"
  #  ports:
  #    - "8080:8080"